FROM node:20-alpine    
#NOME DA IMAGEM
WORKDIR /app           
#DIRETORIO QUE VAI RODAR A APLICACAO
COPY package.json ./   
#COPIAR DESTE DIRETORIO O PACKEGE.JSON PRIMEIRO
RUN npm install        
#INSTALAR O NPM COMO DEPENDENCIA
COPY . .               
#COPIAR DA PASTA LOCAL PARA DENTRO DO CONTEINER
EXPOSE 3000            
#DENTRO DO CONTEINER VAI ESTAR NA PORTA 3000
CMD ["node", "index.js"] 
#EXECUTAR O NODE E O INDEX.JS
