version: '3.9'
# Versão do docker-compose
services:
  db:
# Serviço db dentro do conteiner
    image: postgres:16-alpine
# Imagem do linux que vai ser utizada do linux que ta no dockerhub
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: teste-isolado
#Adicionar Volume de Banco
    volumes:
      - db_data:/var/lib/postgresql/data
# Variaveis do banco do postgree
  api:
# Serviço da api

    build: .
    restart: on-failure
# Compiladar do docker-file que tem dentro desta pasta
    depends_on:
      - db
# Rodar o serviço db antes do api
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/teste-isolado
    ports:
      - "3000:3000"
# variaveis como URL da DATABASE e porta utilizada 3000 dentro do docker e fora do docker é o 3000
volumes:
  db_data:
